server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://180.76.173.202:3306/auth_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: mlzxr
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml